language: python
group: travis_latest

git:
  depth: 3
  quiet: true

os:
  - linux

python:
  - 3.6
#  - 3.7

install:
  - pip install -e .[tests,io]

script: 
  - pytest -sv
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

