language: python
fast_finish: true

os:
  - linux

python: 
  - 3.6
  - 2.7

group: travis_latest

git:
  depth: 3


install:
    - pip -q install -e .[tests]

script: coverage run tests/Test.py -v

after_success: coveralls

