language: python
fast_finish: true

os:
  - linux

python: 
  - 3.6
  - 2.7

notifications:
  email: false

git:
  depth: 3


before_install:
    - pip -q install coveralls

install:
    - pip -q install -e .

script: coverage run tests/test.py -v

after_success: coveralls

